{{- if .Values.openapiGenerator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swagger-editor.fullname" . }}-openapi-generator
  labels:
    {{- include "openapi-generator.labels" . | nindent 4 }}
spec:
  {{- if not .Values.openapiGenerator.autoscaling.enabled }}
  replicas: {{ .Values.openapiGenerator.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "openapi-generator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.openapiGenerator.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openapi-generator.labels" . | nindent 8 }}
        {{- with .Values.openapiGenerator.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "swagger-editor.serviceAccountName" . }}
      {{- with .Values.openapiGenerator.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: openapi-generator-online
          {{- with .Values.openapiGenerator.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.openapiGenerator.image.repository }}:{{ .Values.openapiGenerator.image.tag }}"
          imagePullPolicy: {{ .Values.openapiGenerator.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.openapiGenerator.service.port }}
              name: http
          {{- with .Values.openapiGenerator.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.openapiGenerator.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.openapiGenerator.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.openapiGenerator.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.openapiGenerator.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.openapiGenerator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.openapiGenerator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.openapiGenerator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 