{{- if .Values.swaggerGeneratorv3.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "swagger-editor.fullname" . }}-swagger-generator-v3
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "swagger-generator-v3.componentLabels" . | nindent 4 }}
spec:
  type: {{ .Values.swaggerGeneratorv3.service.type }}
  ports:
    - port: {{ .Values.swaggerGeneratorv3.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "swagger-generator-v3.componentSelectorLabels" . | nindent 4 }}
{{- end }} 