{{- if .Values.swaggerGeneratorv3.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swagger-editor.fullname" . }}-swagger-generator-v3
  labels:
    {{- include "swagger-generator-v3.componentLabels" . | nindent 4 }}
spec:
  {{- if not .Values.swaggerGeneratorv3.autoscaling.enabled }}
  replicas: {{ .Values.swaggerGeneratorv3.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "swagger-generator-v3.componentSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.swaggerGeneratorv3.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "swagger-generator-v3.componentLabels" . | nindent 8 }}
        {{- with .Values.swaggerGeneratorv3.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "swagger-editor.serviceAccountName" . }}
      {{- with .Values.swaggerGeneratorv3.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: swagger-generator-v3
          {{- with .Values.swaggerGeneratorv3.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.swaggerGeneratorv3.image.repository }}:{{ .Values.swaggerGeneratorv3.image.tag }}"
          imagePullPolicy: {{ .Values.swaggerGeneratorv3.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.swaggerGeneratorv3.service.port }}
              protocol: TCP
          {{- with .Values.swaggerGeneratorv3.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.swaggerGeneratorv3.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.swaggerGeneratorv3.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.swaggerGeneratorv3.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.swaggerGeneratorv3.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.swaggerGeneratorv3.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.swaggerGeneratorv3.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.swaggerGeneratorv3.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 