apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swagger-editor.fullname" . }}
  labels:
    {{- include "swagger-editor.labels" . | nindent 4 }}
spec:
  {{- if not .Values.swaggerEditor.autoscaling.enabled }}
  replicas: {{ .Values.swaggerEditor.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "swagger-editor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.swaggerEditor.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "swagger-editor.labels" . | nindent 8 }}
        {{- with .Values.swaggerEditor.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "swagger-editor.serviceAccountName" . }}
      {{- with .Values.swaggerEditor.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.swaggerEditor.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.swaggerEditor.image.repository }}:{{ .Values.swaggerEditor.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.swaggerEditor.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.swaggerEditor.service.port }}
              protocol: TCP
          env:
            {{- if .Values.swaggerEditor.url }}
            - name: URL
              value: "{{ .Values.swaggerEditor.url }}"
            {{- end }}
            {{- if .Values.swaggerEditor.swaggerFile }}
            - name: SWAGGER_FILE
              value: "{{ .Values.swaggerEditor.swaggerFile }}"
            {{- end }}
            {{- if .Values.swaggerEditor.baseUrl }}
            - name: BASE_URL
              value: "{{ .Values.swaggerEditor.baseUrl }}"
            {{- end }}
            {{- if .Values.swaggerEditor.port }}
            - name: PORT
              value: "{{ .Values.swaggerEditor.port }}"
            {{- end }}
            {{- if .Values.swaggerEditor.gtm }}
            - name: GTM
              value: "{{ .Values.swaggerEditor.gtm }}"
            {{- end }}
            - name: URL_SWAGGER2_GENERATOR
              value: {{ if .Values.openapiGenerator.useLocal }}"http://{{ include "swagger-editor.fullname" . }}-openapi-generator:{{ .Values.openapiGenerator.service.port }}/api/swagger.json"{{ else }}"{{ .Values.swaggerEditor.urlSwagger2Generator }}"{{ end }}
            - name: URL_OAS3_GENERATOR
              value: {{ if .Values.openapiGenerator.useLocal }}"http://{{ include "swagger-editor.fullname" . }}-openapi-generator:{{ .Values.openapiGenerator.service.port }}/openapi.json"{{ else }}"{{ .Values.swaggerEditor.urlOas3Generator }}"{{ end }}
            - name: URL_SWAGGER2_CONVERTER
              value: {{ if .Values.openapiGenerator.useLocal }}"http://{{ include "swagger-editor.fullname" . }}-openapi-generator:{{ .Values.openapiGenerator.service.port }}/api/convert"{{ else }}"{{ .Values.swaggerEditor.urlSwagger2Converter }}"{{ end }}
          {{- with .Values.swaggerEditor.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.swaggerEditor.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.swaggerEditor.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.swaggerEditor.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.swaggerEditor.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.swaggerEditor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.swaggerEditor.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.swaggerEditor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
