{{- if .Values.swaggerConverterv1.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swagger-editor.fullname" . }}-swagger-converter-v1
  labels:
    {{- include "swagger-converter-v1.componentLabels" . | nindent 4 }}
spec:
  {{- if not .Values.swaggerConverterv1.autoscaling.enabled }}
  replicas: {{ .Values.swaggerConverterv1.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "swagger-converter-v1.componentSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.swaggerConverterv1.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "swagger-converter-v1.componentLabels" . | nindent 8 }}
        {{- with .Values.swaggerConverterv1.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "swagger-editor.serviceAccountName" . }}
      {{- with .Values.swaggerConverterv1.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: swagger-converter-v1
          {{- with .Values.swaggerConverterv1.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.swaggerConverterv1.image.repository }}:{{ .Values.swaggerConverterv1.image.tag }}"
          imagePullPolicy: {{ .Values.swaggerConverterv1.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.swaggerConverterv1.service.port }}
              protocol: TCP
          {{- with .Values.swaggerConverterv1.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.swaggerConverterv1.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.swaggerConverterv1.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.swaggerConverterv1.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.swaggerConverterv1.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.swaggerConverterv1.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.swaggerConverterv1.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.swaggerConverterv1.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 