{{- if .Values.swaggerGeneratorv2.enabled -}}
{{- if and .Values.swaggerGeneratorv2.istio.gateway.tls .Values.swaggerGeneratorv2.istio.gateway.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.swaggerGeneratorv2.istio.gateway.certManager.certificateName | default (printf "%s-swagger-generator-v2-cert" (include "swagger-editor.fullname" .)) | quote }}
  namespace: {{ if .Values.swaggerGeneratorv2.istio.gateway.certManager.namespace }}{{ .Values.swaggerGeneratorv2.istio.gateway.certManager.namespace | quote }}{{ else if .Values.swaggerGeneratorv2.istio.gateway.namespace }}{{ .Values.swaggerGeneratorv2.istio.gateway.namespace | quote }}{{ else }}{{ .Release.Namespace | quote }}{{ end }}
spec:
  secretName: {{ .Values.swaggerGeneratorv2.istio.gateway.tlsSecret | default .Values.swaggerGeneratorv2.istio.gateway.certManager.certificateName | default (printf "%s-swagger-generator-v2-cert" (include "swagger-editor.fullname" .)) | quote }}
  issuerRef:
    name: {{ .Values.swaggerGeneratorv2.istio.gateway.certManager.issuerName | default "letsencrypt-prod" | quote }}
    kind: {{ .Values.swaggerGeneratorv2.istio.gateway.certManager.issuerKind | default "ClusterIssuer" | quote }}
  dnsNames:
    {{- range .Values.swaggerGeneratorv2.istio.gateway.hosts }}
    - {{ . | quote }}
    {{- end }}
{{- end }}
{{- end }} 