{{- if .Values.swaggerGeneratorv2.enabled -}}
{{- if .Values.swaggerGeneratorv2.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "swagger-editor.fullname" . }}-swagger-generator-v2
  labels:
    {{- include "swagger-generator-v2.componentLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "swagger-editor.fullname" . }}-swagger-generator-v2
  minReplicas: {{ .Values.swaggerGeneratorv2.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.swaggerGeneratorv2.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.swaggerGeneratorv2.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.swaggerGeneratorv2.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.swaggerGeneratorv2.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.swaggerGeneratorv2.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }} 