{{- if .Values.swaggerEditor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "swagger-editor.fullname" . }}-swagger-editor
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "swagger-editor.componentLabels" . | nindent 4 }}
spec:
  type: {{ .Values.swaggerEditor.service.type }}
  ports:
    - port: {{ .Values.swaggerEditor.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "swagger-editor.componentSelectorLabels" . | nindent 4 }}
{{- end }}
