{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "swagger-editor.fullname" . }}-vs
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "swagger-editor.labels" . | nindent 4 }}
spec:
  hosts:
    {{- toYaml .Values.istio.virtualService.hosts | nindent 4 }}
  gateways:
    {{- toYaml .Values.istio.virtualService.gateways | nindent 4 }}
  http:
    - match:
        - uri:
            prefix: {{ .Values.istio.virtualService.path | quote }}
      rewrite:
        uri: {{ .Values.istio.virtualService.rewrite | quote }}
      route:
        - destination:
            host: {{ include "swagger-editor.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }} 